import java.nio.charset.StandardCharsets;
import java.nio.file.*;

public class SpecMethodLogicAppender {

    public static void main(String[] args) throws Exception {
        Args a = Args.parse(args);
        if (!a.ok()) { Args.usage(); return; }

        Path specPath = Paths.get(a.specFile).toAbsolutePath().normalize();
        if (!Files.exists(specPath)) {
            System.err.println("[ERROR] No such spec file: " + specPath);
            return;
        }

        Path logicPath = Paths.get(a.logicFile).toAbsolutePath().normalize();
        if (!Files.exists(logicPath)) {
            System.err.println("[ERROR] No such logic file: " + logicPath);
            return;
        }

        String json  = Files.readString(specPath, StandardCharsets.UTF_8);
        String logic = Files.readString(logicPath, StandardCharsets.UTF_8).trim();

        if (logic.isEmpty()) {
            System.err.println("[WARN] Logic file is empty, nothing to do.");
            return;
        }

        String logicBlock = buildNewMethodLogicSpecBlock(logic);

        // We assume spec was generated by ClassToSpecJsonFile and has no existing newMethodLogicSpec.
        // Insert before the final "}\n"
        int idx = json.lastIndexOf("\n}\n");
        if (idx < 0) {
            // Fallback: last '}' position
            idx = json.lastIndexOf('}');
            if (idx < 0) {
                throw new IllegalStateException("Spec JSON does not look valid / no closing brace found.");
            }
            String prefix = json.substring(0, idx).trim();
            String suffix = json.substring(idx);
            json = prefix + ",\n" + logicBlock + "\n" + suffix;
        } else {
            String prefix = json.substring(0, idx).trim();
            String suffix = json.substring(idx); // "\n}\n"
            json = prefix + ",\n" + logicBlock + suffix;
        }

        // Always overwrite the same spec file
        Files.writeString(specPath, json, StandardCharsets.UTF_8);
        System.out.println("[OK] Updated spec with newMethodLogicSpec: " + specPath.toAbsolutePath());
    }

    // ---------- Args ----------
    static final class Args {
        String specFile;   // required
        String logicFile;  // required

        static Args parse(String[] av) {
            Args a = new Args();
            for (int i = 0; i < av.length; i++) {
                switch (av[i]) {
                    case "--specFile" -> {
                        if (i + 1 < av.length) a.specFile = av[++i];
                    }
                    case "--logicFile" -> {
                        if (i + 1 < av.length) a.logicFile = av[++i];
                    }
                }
            }
            return a;
        }

        boolean ok() { return specFile != null && logicFile != null; }

        static void usage() {
            System.out.println("""
                SpecMethodLogicAppender - add newMethodLogicSpec to an existing *_spec.json,
                loading the logic from a text file.

                Usage:
                  java SpecMethodLogicAppender --specFile Dori_spec.json \\
                      --logicFile logic.txt

                Where:
                  - --specFile   points to an existing *_spec.json produced by ClassToSpecJsonFile
                  - --logicFile  is a UTF-8 text file whose entire contents are a natural-language
                                  description of ONE new method you want OpenAI to generate.

                Notes:
                  - The logic text is stored under the key "logic_1" inside newMethodLogicSpec.
                  - The spec file is modified in-place (overwritten).
            """);
        }
    }

    // ---------- Build newMethodLogicSpec from a single logic string ----------
    static String buildNewMethodLogicSpecBlock(String logic) {
        StringBuilder sb = new StringBuilder();
        sb.append("  \"newMethodLogicSpec\": {");
        sb.append("\n    ")
          .append(js("logic_1"))
          .append(": ")
          .append(js(logic));
        sb.append("\n  }");
        return sb.toString();
    }

    static String js(String s) {
        if (s == null) return "null";
        return "\"" + s.replace("\\", "\\\\").replace("\"", "\\\"") + "\"";
    }
}
